dist: trusty

language: cpp
compiler: gcc
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ../
  - make
