language: cpp

matrix:
  include:
    - os: linux
      dist: focal
      compiler: gcc
    - os: osx
      compiler: clang

script:
  - cmake -S. build
  - cd build
  - cd v2xmessage
  - make
  - ctest
  - cd ../
  - cd v2verifier-app
  - make
  - ctest
  - cd ../
