language: cpp

matrix:
  include:
    - os: linux
      dist: focal
      compiler: gcc
    - os: osx
      compiler: clang

script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ../
  - make
